const DIFFICULTY = 3;
const MINE_RATE = 3000;
const INITIAL_BALANCE = 500;
const MINING_REWARD = 50;
const NODE = "http://localhost:3000"

module.exports = { DIFFICULTY, MINE_RATE, INITIAL_BALANCE, MINING_REWARD, NODE};